### ISSUE TITLE
Compiling on Apple Silicon

### ISSUE THREAD

**Issue by tquatmann** [moves-rwth/storm#274]
I propose to document the current state of compiling on apple silicon in this issue.

Once PR #273 is merged, Storm compiles natively on apple M1. However, some tweaks are likely necessary. Here is what worked for me:

* Install dependencies (again) using the *arm* version of homebrew. Skip `cln` and `ginac` as these are not supported by homebrew
* Make sure that you use an arm compiled `cmake` binary (check with `where cmake` and `file path/to/cmake`)
* Build carls `master14` branch without cln and ginac (`make lib_carl` suffices)
* When configuring storm, set cmake option `-DSTORM_PORTABLE=ON`

> Hint: when building x86 versions, I now set `-DSTORM_FORCE_SHIPPED_CARL=ON` as we can't use the arm installation

## TODO list for official support:

- [ ] merge PR #273 
- [ ] make installation of carl and storm without cln and ginac more straightforward (ideally, these dependencies are disabled automatically if compiling on M1 is detected).
- [ ] I had problems with setting `-DSTORM_FORCE_SHIPPED_CARL=ON` when compiling for arm: carl did not compile due to some eigen related issue.
- [ ] Some includes are taken from the x86 installation. For example, I ran into a known issue related to boost that should have already been fixed in my boost installation. The "solution" was  to upgrade my x86 boost installation.
- [ ] clang option `-march=native` does not seem to work yet which is why `-DSTORM_PORTABLE` was required for me. Also, the jit engine doesn't work for that reason, which also lets the tests fail
- [ ] The Homebrew formula(s) for Storm and Carl need to be updated as well
- [ ] Adapt Website documentation

**Comment by sjunges** [comment]
Hi Tim,

great progress. Could you add an item regarding stormpy on the TODO list. At least it would be good if we have clarity on whether this will work when writing the documentation. 

Do we already detect M1/ARM64 architectures in CMake?

**Comment by sjunges** [comment]
Regarding CLN: https://www.ginac.de/pipermail/cln-list/2023-March/000803.html, there seems to be some progress

**Comment by tquatmann** [comment]
I'm compiling on Apple Silicon just fine and I can no longer reproduce the issues I had before when using a shipped carl version. I guess that problem solved itself.

The test `SparseMaPcaaMultiObjectiveModelCheckerTest.serverRationalNumbers` fails due to an issue in Eigen `v3.3.9`. I worked around this in PR #349

**Comment by sjunges** [comment]
CLN support is still lagging behind; one could appearantly install this from git: https://www.ginac.de/pipermail/cln-list/2023-April/000815.html

**Comment by sjunges** [comment]
I have been using this with stormpy now for quite some while :-)

**Comment by sjunges** [comment]
The typical problem that people seem to run into is that libraries compiled for x86/Rosetta are included, which leads to strange errors down the line. I wonder if there is a simple way to spot this during configuration. 

It would definitively help resolve https://github.com/moves-rwth/storm/issues/419

**Comment by sjunges** [comment]
Can we add https://github.com/moves-rwth/storm/issues/354 this to the checklist here?

**Comment by tquatmann** [comment]
I just installed storm w/ CLN support. Seems to work so far :)

**Comment by sjunges** [comment]
Can we add https://github.com/moves-rwth/storm/issues/523 to the issues?

**Comment by sjunges** [comment]
Bug #523 has been resolved by single-thread sylvan, see #600  which relates to this.

**Comment by sjunges** [comment]
Yes, we are. We have trouble with the transactional memory implementation on the ARMs as the memory model differs from the assumptions one can make on x86_64. Maybe @dbasgoeze can point to specifics?

**Comment by dbasgoeze** [comment]
Yea, at least one of the problem is [cache_get](https://github.com/trolando/sylvan/blob/master/src/sylvan_cache.c#L166)

```(c)
    const uint32_t s = atomic_load_explicit(s_bucket, memory_order_relaxed);
    // abort if locked or if part of a 2-part cache entry
    if (s & 0xc0000000) return 0;
    // abort if different hash
    if ((s ^ (hash>>32)) & 0x3fff0000) return 0;
    // abort if key different
    if (bucket->a != a || bucket->b != b || bucket->c != c) return 0;
    *res = bucket->res;
    // abort if status field changed after compiler_barrier()
    return atomic_load_explicit(s_bucket, memory_order_acquire) == s ? 1 : 0;
```

Here the last atomic_load_explicit can be reordered right after the load in the first atomic load in the first line. That alone can lead to inconsistent memory accesses in the operation cache. Keep in mind that this can happen even if the assembly does "the right thing" ™ as the CPU can still reorder the reads.

On the x86 this is fine as the memory model of the processor guarantees that if you read the value written by another thread you also see everything the other thread wrote before and the compiler does the right thing here, i.e. as far as I have observed did not reorder the reads in the compiled assembly.

For example:

A begins reading.
B changes the tag to indicate that it will write
B writes
A reads something B has written <- (here the sync happens and A sees B's write to the tag -- this is the guarantee of the strong memory model of the x86)
A will now read that the tag has been changed
[Not important but here A *will* be able to read everything B wrote because of the memory_order_acquire]


On ARM this guarantee is not there anymore as its memory model is weaker than the relatively strong x86 one.

For example:

A begins reading.
B changes the tag to indicate that it will write
B writes
A reads something B has written <- (here no sync is performed)
A does not read that the tag has been changed <- (this is now out of order)
[Not important but no acquire release semantic apply here as the memory_order_acquire load did not read anything B wrote. ]

**Comment by dbasgoeze** [comment]
- no reads are reordered before the first status read, and
 - no reads are reordered after the second status read.

Is not enough. In a weak memory model you can read something out of order.

The order is you require above. So no load before the first and no load after the second. This will still fail.

A reads the status field
B writes to the status field
B writes to the data protected by the status field
A reads data that is protected by the status field written by B
A does not read the write to the status field of B

This is possible in a weak memory model and satisfies your order requirements.

I think a seq_cst fence could maybe work here but that will tank performance as the whole cpu bus needs to be locked.

**Comment by dbasgoeze** [comment]
I would be very careful with empirical tests for this as the implementation (i.e. compiler and/or cpu) can strengthen the guaranteed memory model on a whim (the right kind of branching pattern for example or access in a cache line near another important one).

A weak memory model can sometimes behave like a strong one but that does not mean that it will in all situations.

**Comment by trolando** [comment]
Ehm in your example 
>A reads the status field
B writes to the status field
B writes to the data protected by the status field
A reads data that is protected by the status field written by B
A does not read the write to the status field of B

Wouldn't A read in step 5 the update to the status field from step 2? Why not?

Maybe what you mean is that the stores could be reordered? In your specific interleaving, things would go well. What about this:

1. A loads status field
2. memory fence
3. A loads protected data
4. memory fence
5. A loads status field
 
Runs concurrently with

1. B stores status field ("locked for writing")
2. B stores protected data
3. B stores status field ("writing done, here's the new hash")

Could in theory be reordered to

1. A loads status field
2. B stores protected data
3. A loads protected data
4. B stores status field ("locked for writing")
5. B stores status field ("writing done, here's the new hash")
6. A loads status field

**Comment by dbasgoeze** [comment]
> Wouldn't A read in step 5 the update to the status field from step 2? Why not?

Because in a weak memory model threads can see memory accesses of other threads in different orders than they do. There is no global order (seq_cst is the only memory order that enforces a global order on other seq_cst accesses).

What kind of memory fence is used in your example? seq_cst?

**Comment by trolando** [comment]
> I would be very careful with empirical tests for this as the implementation (i.e. compiler and/or cpu) can strengthen the guaranteed memory model on a whim (the right kind of branching pattern for example or access in a cache line near another important one).
> 
> A weak memory model can sometimes behave like a strong one but that does not mean that it will in all situations.

Oh yes I agree, I still wanted to write some code and try it out.  I think the safest solution is `acquire` on the first read, that would definitely prevent doing the loads too early, and the `seq_cst` fence before the second `relaxed` read... well, if you claim that this isn't enough, then the conclusion is simply that it's flat out impossible to make a seqlock with C11 atomics.

**Comment by trolando** [comment]
> Because in a weak memory model threads can see memory accesses of other threads in different orders than they do. There is no global order (seq_cst is the only memory order that enforces a global order on other seq_cst accesses).

What if I'm only interested in supporting standard x86 chips and Apple chips?
I'm not familiar with anything else anyway. Are there very weak memory models used for large scientific calculations?

> What kind of memory fence is used in your example? seq_cst?

Eh yeah just the strongest one, the point was that store reordering could cause problems, but I guess even with properly ordered stores, they might not be visible in the same order indeed. Which as far as I'm aware is not something that happens in x86 or Apple chips?

**Comment by trolando** [comment]
Right, so if every load/write is `seq_cst` it would work? That would indeed completely kill performance and on x86 or ARM it would be completely unnecessary as far as I know?

**Comment by dbasgoeze** [comment]
Non performant and correct would be I think:
cache_put must write to the status register with seq_cst but data still as it is now.
cache_get like you stated earlier:

> Oh yes I agree, I still wanted to write some code and try it out. I think the safest solution is acquire on the first read, that would definitely prevent doing the loads too early, and the seq_cst fence before the second relaxed read...

**Comment by trolando** [comment]
Well, I just tried that and there _seems_ to be no big performance impact. I tested Sylvan with `bddmc` on the `schedule_world.3` model, using 20 workers on my x86, Intel Core i5-13600KF (6 performance cores with 2 threads, 8 energy cores)

- `put` uses `compare_and_swap`  with `seq_cst` for the first write, and `release` ordering for the second write.
- `get` uses `acquire`  for the first read, and a `seq_cst` thread fence before the `relaxed` second read

All reads/writes of protected data are standard.

This does not seem to impact this one benchmark at all on my PC, or if it does, it's not noticeable.

```
Sylvan statistics
Tables
MTBDD nodes created  240,467,575     
MTBDD nodes reused   385,043,526     
Lookup iterations    1,793,377,414   
Unique nodes table   11,183,636 of 268,435,456 buckets filled.
Operation cache      24,693,105 of 134,217,728 buckets filled.
Memory (nodes)       6.000 GB (max real) of 6.000 GB (allocated virtual memory).
Memory (cache)       4.500 GB (max real) of 4.500 GB (allocated virtual memory).

Operation            Count            Cache get        Cache put
BDD and              502,474,970      435,932,309      63,696,894      
BDD relnext          329,428,233      278,521,101      49,805,526      
BDD satcount         133,786          96,739           18,644          

Garbage collection
GC executions        6               
Total time spent     1.071854 sec.
```

BTW I don't really protect against tears either but all the data is aligned and so far no one complained about tearing.

**Comment by dbasgoeze** [comment]
What is the disassembly of the cache_get?

**Comment by dbasgoeze** [comment]
Yea I concur with the annotations. Should work. Can it be that in the benchmark the fence is not executed frequently? I.e. how does the successful cache hit rate look like?

**Comment by trolando** [comment]
Well as you can see...
```
Operation            Count            Cache get        Cache put
BDD and              502,474,970      435,932,309      63,696,894      
BDD relnext          329,428,233      278,521,101      49,805,526      
BDD satcount         133,786          96,739           18,644          
```

A "cache get" result is a successful operation, whereas "count" states how often an operation performed. So about 87% successful cache, that's quite good actually. That's for the `and` operation.

**Comment by trolando** [comment]
What's happening is that I finally have a bit of time to do some maintenance on Sylvan instead of drowning in education preparation (thanks @marieke73 and @fernandocastor), so I'm now drowning in years-old Sylvan issues and maintenance requests instead :-) I also need to submit something to ETAPS next year to make @sjunges happy so I guess it'll be Sylvan 2.0...

**Comment by trolando** [comment]
I've released version v1.9.0 of Sylvan, which fixes this particular bug.

**Comment by dbasgoeze** [comment]
I think that could work, but I think the loads in line 4 of the Cache-Get need to be atomic (with any ordering so they can be relaxed).

The C standard says 7.14.4.4:
> An atomic operation A that is a release operation on an atomic object M synchronizes with an acquire fence B if there exists some atomic operation X on M such that X is sequenced before B
> and reads the value written by A or a value written by any side effect in the release sequence headed
> by A.

- The atomic operation A here is line 6 of Cache-Put.
- M is the status field
- B is line 5 of Cache-get

Now the only thing missing is X on M such that X is sequenced before B and reads the value written by A or a value written by any side effect in the release sequence headed by A.

As far as I know the writes in line 5 of cache-put are written by the release sequence headed by A.

Therefore if the reads in line 4 of the cache-get were atomic operations they would fit the bill to be X.

**Comment by trolando** [comment]
It is explained here: https://preshing.com/20130922/acquire-and-release-fences/

The acquire fences prevent Load-Load and Load-Store reordering and the release fences prevent Load-Store and Store-Store reordering.

So in your example, you state that the get_6 is reordered before get_4, but the acquire _fence_ would prevent this. In addition, put_3 cannot be reordered after put_5 because the CAS is an acquire operation on success. The get_6 _will_ see put_3. 

I concede that _maybe_ the CAS should be acq_rel on success rather than just acquire.

**Comment by sjunges** [comment]
Only https://github.com/stormchecker/storm/issues/600 remains, so we can close this issue.
